@startuml
:Start;
:Next step;
:Final step;
if (Your decision) then (Yes)
: Yes;
else (Nope)
:Nope;
endIf
:New step after If;
:Another new step;
:Second another step;
if (Your decision) then (Yes)
: Yes;
else (Nope)
:No no no;
endIf
end
@enduml
